export const Types = {
	FETCH_USERS_START: 'FETCH_USERS_START',
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
	SORT_USERS: 'SORT_USERS',
	FILTER_USERS: 'FILTER_USERS',
	CHANGE_PAGE: 'CHANGE_PAGE',
	CHANGE_ROWS_PER_PAGE: 'CHANGE_ROWS_PER_PAGE',
};
